site_name: Flask-Authlib
site_url: http://abduazizziyodov.github.io/flask_authlib
site_description: Flask-Authlib - Authentication Library For Flask Web Framework 🔥

repo_name: flask-authlib
repo_url: https://github.com/AbduazizZiyodov/flask-authlib

edit_uri: ""

theme:
  favicon: assets/favicon.ico

  icon:
    logo: fontawesome/brands/python
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  name: material
  palette:
    - scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.top

plugins:
  - search:
      lang: en

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AbduazizZiyodov/flask-authlib
      name: See this project on Github
    - icon: fontawesome/brands/telegram-plane
      link: https://t.me/AbduazizZiyodov
      name: Author's Telegram Account
copyright: Copyright &copy; 2021 Abduaziz Ziyodov

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Intro: index.md
  - Tutorial - User Guide:
      - Basic Usage of Library: user-guide/basic_usage.md
      - Customization:
          - Customize Base Settings: user-guide/base_config.md
          - Customize Alerts: user-guide/alerts_config.md
          - Customize Templates: user-guide/templates_config.md
  - Flask For Beginners:
      - flask_tutorials/getting_started.md
      - flask_tutorials/running_application.md
      - flask_tutorials/routing.md
      - flask_tutorials/http_methods.md
      - flask_tutorials/templates.md
      - flask_tutorials/request_handling.md

extra_css:
  - css/custom.css
